name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to build for (staging or production)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: downcase IMAGE_NAME
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Checkout shared workflows
        uses: actions/checkout@v4.2.2
        with:
          repository: BenaroyaResearch/shared-workflows
          path: shared-workflows
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Extract versions from package.json
        run: |
          chmod +x shared-workflows/.github/extract-versions.sh
          shared-workflows/.github/extract-versions.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ inputs.environment == 'production' && 'type=ref,event=branch' || '' }}
            ${{ inputs.environment == 'production' && 'type=semver,pattern={{version}}' || '' }}
            ${{ inputs.environment == 'staging' && 'type=raw,value=staging-{{sha}}-{{date ''YYYYMMDDHHmmss'' tz=''America/Los_Angeles''}}' || '' }}
            ${{ inputs.environment == 'staging' && 'type=raw,value=staging' || '' }}

      - name: Build and push final image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          build-args: |
            NODE_ENV=${{ inputs.environment }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            PNPM_VERSION=${{ env.PNPM_VERSION }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            "font_awesome_token=${{ secrets.FONTAWESOME_TOKEN }}"
