name: stg-ci

on:
  workflow_call:

jobs:
  staging:
    uses: BenaroyaResearch/shared-workflows/.github/workflows/build-and-push.yaml@main
    with:
      environment: staging
      docker-tags: |
        type=raw,value=staging-{{sha}}-{{date 'YYYYMMDDHHmmss' tz='America/Los_Angeles'}}
        type=raw,value=staging
    secrets: inherit
