name: prod-ci

on:
  workflow_call:

jobs:
  production:
    uses: BenaroyaResearch/shared-workflows/.github/workflows/build-and-push.yaml@main
    with:
      environment: production
      docker-tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
    secrets: inherit
